### ISSUE TITLE
Authentication and security documentation

### ISSUE THREAD

**Issue by joahim** [jonathan-s/django-sockpuppet#104]
Is there information or examples available on how to properly secure the reflexes/websockets? For example, how to implement the CSRF websocket protection or how to authenticate the user prior to opening the websocket.

**Comment by jonathan-s** [comment]
> how to authenticate the user prior to opening the websocket
If the user already is logged in the normal way in django. The user is already authenticated. Does that answer your question? 

With regards to the other websocket protection, yeah, some more documentation around that area would be needed there.

**Comment by joahim** [comment]
The way I understand this is that if user is authenticated you show them the page with the sockpuppet code. But I guess you should probably still check the authentication on the socket connection to cover the case the user connects to the websocket directly?

Also, I noticed socketpuppet is using django-channels and their documentation nicely describes how to protect for CSRF (https://channels.readthedocs.io/en/stable/topics/security.html). I think it would be useful to allow or direct users how to reach into this part of the code and implement this logic (or even make it the default). On the other hand, I noticed django-unicorn requires csrf_token by default so that might also be a good solution.

I do apologize if I'm talking nonsense here since I'm not at all experienced with websockets. And since this is (at this time) probably true for many other django users I think having a solid protection built in as a default might be a good approach.

**Comment by jonathan-s** [comment]
Note to self, when dealing with this issue incorporate @fmalina's comment in #102

**Comment by jonathan-s** [comment]
@joahim, I've now merged a PR that adds the documentation and uses the origin validator by default. Let me know if you've got any questions or suggestions here!
