### ISSUE TITLE
context['stimulus_reflex'] KeyError

### ISSUE THREAD

**Issue by paulik123** [jonathan-s/django-sockpuppet#107]
# Bug Report

In the documentation it says: 
When Sockpuppet calls your Django view, it passes any active instance variables along with a special context variable called stimulus_reflex, which is set to true. You can use this context variable to create an if/else block in your template or view that behaves differently depending on whether it's being called within the context of a Reflex update or not.

But if I write:
`if not context['stimulus_reflex']:`
in the view, I get a KeyError and even if i try to use `context.get('stimulus_reflex')` that doesn't help because the context never gets updated with that key.

**Comment by jonathan-s** [comment]
Thanks for reporting this!
