### ISSUE TITLE
afterReflex, reflexSuccess, reflexError don't trigger if the element which "caused" the reflex isn't present on the page after the reflex..

### ISSUE THREAD

**Issue by paulik123** [jonathan-s/django-sockpuppet#133]
As the title suggets. I'm not sure if it's a bug, or if this is the intended functionality.

**Comment by jonathan-s** [comment]
Yes that's expected > https://docs.stimulusreflex.com/appendices/troubleshooting#dont-modify-the-dom-in-the-middle-of-a-reflex

I should make sure that piece of docs is in sockpuppet as well.
