### ISSUE TITLE
Update Ruby examples to Django

### ISSUE THREAD

**Issue by OmenApps** [jonathan-s/django-sockpuppet#23]
### Description

Some or all of the server-side code examples on the following documentation pages are .rb or .erb files, and need to be rewritten as .py

- https://sockpuppet.argpar.se/patterns
- https://sockpuppet.argpar.se/deployment
- https://sockpuppet.argpar.se/persistence
- https://sockpuppet.argpar.se/lifecycle

**Comment by jonathan-s** [comment]
Thank you for opening this issue!
