### ISSUE TITLE
Triggering a 500 error won't give frontend notice that such an error happened

### ISSUE THREAD

**Issue by jonathan-s** [jonathan-s/django-sockpuppet#3]
If you are an anonymous user and happen to trigger a 500 error no session key has yet been created. The session key is created first after the page has been rendered. Because of that the consumer sends the error message into an empty void where no frontend will ever receive the message. 

Errors that should otherwise be covered when user is logged in, and should be covered by tests. 
- Frontend should be notified when a reflex gets the reflex name wrong
- Frontend should know when we get a type error
- Frontend should know when we get some other kind of reflex error.

**Comment by JulianFeinauer** [comment]
As discussed in discord (just for the notice here).. one issue is that when the exception is raised the WS channel gets closed. So the broadcast to the client is not sent out.

**Comment by jonathan-s** [comment]
Does not seem to be an issue any more! So closed by #74
