### ISSUE TITLE
scaffolding a reflex produces wrong class name when it contains a _

### ISSUE THREAD

**Issue by nerdoc** [jonathan-s/django-sockpuppet#84]
When creating a reflex using the  management command, it works as long as you don't use a `_` in your reflex name. assuming you have an ap pnamed `core`, start

    ./manage.py generate_reflex core foo_bar

It creates the corresponding files, but according to your javascript it calls the reflex `Foo_BarReflex`

```javascript
    <a
      href="#"
      data-reflex="click->Foo_BarReflex#increment"
      data-count="{{ count }}"
    >Increment </a><span>{{ count }}</span>
```

When you look at the class:

```python
class FooBarReflex(Reflex):
    def increment(self, step=1):
        self.count = int(self.element.dataset['count']) + step
```
Which can't be found. When removing the _ in the `data-reflex` attr, it works.
The generator shouldn't add this underline.

**Comment by nerdoc** [comment]
The error is in the `camelize()` function. Technically, this function does not camelize, but "pascalize" words. If you want I can make a PR to fix that?

**Comment by nerdoc** [comment]
There is a function in graphene_django which borrows from http://stackoverflow.com/a/19053800/1072990 - I would use that here?

**Comment by nerdoc** [comment]
all over the place in templates you are using `{{ reflex_name|title }}`for generating the names. If a `reflex_name` contains a _, this produces the problematic result.

**Comment by nerdoc** [comment]
Also when "using javascript" (like your templates say), you [define ](https://github.com/jonathan-s/django-sockpuppet/blob/dd6ed2fd25273850ad1ba3274fb7afe5b9cdc53b/sockpuppet/templates/sockpuppet/scaffolds/template.html#L10)

```javascript
    data-action="click->{{ reflex_name }}#increment"
```

and a few lines below in the block "without" custom javascript, you [write](https://github.com/jonathan-s/django-sockpuppet/blob/dd6ed2fd25273850ad1ba3274fb7afe5b9cdc53b/sockpuppet/templates/sockpuppet/scaffolds/template.html#L18)

```javascript
            data-reflex="click->{{ reflex_name|title}}Reflex#increment"
```

with the "Reflex" in the name. So 2 different versions, but the Reflex class is always named the same in the scaffolding process...

I wrote a small patch which creates 2 custom Django template filters named "camelcase" and "pascalcase" which you could use within your `templatetags/sockpuppet" - nothing to add further. you could even use that for your other templates too and get rid of your camelcase function (which imports `re`)

I don't know if all the tests are passing, as the current behaviour IS faulty and passes the tests... ;-)

It would then look much smoother:
```javascript
      data-reflex="click->{{ reflex_name|pascalcase }}Reflex#increment"
```

and the filters:

```python
@register.filter(name="camelcase")
def camelcase(value) -> str:
    components = value.split("_")
    # We capitalize the first letter of each component except the first one
    # with the 'capitalize' method and join them together.
    return components[0] + "".join(x.capitalize() if x else "_" for x in components[1:])


@register.filter(name="pascalcase")
def pascalcase(value):
    components = value.split("_")
    # We capitalize the first letter of each component
    # with the 'capitalize' method and join them together.
    return "".join(x.capitalize() if x else "_" for x in components)
```

If you like I can make a PR.

**Comment by DamnedScholar** [comment]
Looks like a very solid addition to me.

**Comment by jonathan-s** [comment]
Seal of approval. If you are able to write some more tests for what is expected that would also be a welcome addition.

**Comment by nerdoc** [comment]
Ah, yes. I was there in the first place, and would have written some tests too. But (I should file another issue...):
Your testing instructions at https://github.com/jonathan-s/django-sockpuppet/tree/master/tests are not applicable. 

* There is no manage.py nor requirements.txt in tests/example - requirements.txt is in tests/, and manage.py is not there (forgot to commit?) So the example project can't be started "easily". 
* Even when I add a manage.py and can run the test example, it has dozens of errors, the test suite "./mnage.py test" fails because of missing webpack, etc. So which kinds of tests should I write - where ;-)
* etc.

May I suggest something. In my [GDAPS](https://gitlab.com/nerdocs/gdaps/-/tree/master/tests) project I use pytest over Django unittests - they are more convenient to write, and pytest can run Django unittests too. Look at my tests/ directory there.
If you would be inclined "switching" to pytest (which most people do nowadays), I would write the tests as pytest tests - and help set up a pytest suite. How do you do your integration tests? You have a test server/CI running - doesn't it use this test/example project?

**Comment by nerdoc** [comment]
Eh, and would i be a possibility to remove webpack etc from the test project? It complicates things, and doesn't help anything testing django-sockpuppet...?

**Comment by nerdoc** [comment]
OMG. sorry for my mass posts here - your manage.py and everything is in the root dir. works...
